
package sistemanortfarma;
import CapaLogica.LogicaVenta;
import entidad.Venta;
import CapaLogica.LogicaProforma;
import entidad.ResultadoVenta;
import java.awt.Color;
import java.awt.event.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import javax.swing.*;
import java.awt.*;

import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author gparedes
 */
public class Recuperavtasoat extends javax.swing.JInternalFrame {

    AplicacionVentas objventas;
    
    //addKeyListener(this);
    String interno;
    List<Venta> listaInternos = new ArrayList<Venta>();
    List<Venta> listaVenta = new ArrayList<Venta>();
    LogicaVenta logventa = new LogicaVenta();
    LogicaProforma onjproforma = new LogicaProforma();
    LogicaVenta objguardaventa = new LogicaVenta();
    Object[] datosDetalle = new Object[6];
    private DefaultTableModel model;
    TableColumnModel colModel1;
    MuestraVentana objetoventana = new MuestraVentana();
    double total = 0;
    double subtotal = 0;
    double igv = 0;
    Venta obj;
    private String idventa = "";
    private String idbotica = null;
    Object[] datosDetalle_1 = new Object[7];
    
    /** Creates new form Recuperavtasoat */
    public Recuperavtasoat(AplicacionVentas obj) {
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemanortfarma/resources/busyicons/tab_edit.png")));

        initComponents();

        objventas = obj;
        idbotica = objventas.getIdbotica();
        model = (DefaultTableModel) jTable1.getModel();
        colModel1 = jTable1.getColumnModel();
        AparienciaTabla();
        this.txtcajero.setBackground(new Color(255, 255, 255));
        this.txtigv.setBackground(new Color(255, 255, 255));
        this.txtnumero.setBackground(new Color(255, 255, 255));
        this.txtserie.setBackground(new Color(255, 255, 255));
        this.txtsubtotal.setBackground(new Color(255, 255, 255));
        this.txttipoventa.setBackground(new Color(255, 255, 255));
        this.txttotal.setBackground(new Color(255, 255, 255));
        this.txtvendedor.setBackground(new Color(255, 255, 255));
        Oculta_Botones(false);
        jButton3.setEnabled(false);
        setResizable(false);
        txtpoliza.setEnabled(true);
    }

    private void AparienciaTabla() {

        JTableHeader cabecera = new JTableHeader(this.jTable1.getColumnModel());
        cabecera.setReorderingAllowed(false);

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);

        DefaultTableCellRenderer tleft = new DefaultTableCellRenderer();
        tleft.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(tleft);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(tleft);

    }

    private void Oculta_Botones(boolean valor) {        
        jButton4.setEnabled(valor);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txttipoventa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        txtigv = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtserievehi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtpoliza = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtcertificado = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtvendedor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtcajero = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sistemanortfarma.SistemaNortfarmaApp.class).getContext().getResourceMap(Recuperavtasoat.class);
        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextField1.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txttipoventa.setEnabled(false);
        txttipoventa.setName("txttipoventa"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txtserie.setEnabled(false);
        txtserie.setName("txtserie"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        txtnumero.setEnabled(false);
        txtnumero.setName("txtnumero"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Producto", "UND", "FRACC", "PVPx", "Parcial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setEnabled(false);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        txtsubtotal.setFont(resourceMap.getFont("txtsubtotal.font")); // NOI18N
        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsubtotal.setEnabled(false);
        txtsubtotal.setName("txtsubtotal"); // NOI18N

        txtigv.setFont(resourceMap.getFont("txtigv.font")); // NOI18N
        txtigv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtigv.setEnabled(false);
        txtigv.setName("txtigv"); // NOI18N

        txttotal.setFont(resourceMap.getFont("txttotal.font")); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotal.setEnabled(false);
        txttotal.setName("txttotal"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        txtserievehi.setForeground(resourceMap.getColor("txtserievehi.foreground")); // NOI18N
        txtserievehi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtserievehi.setEnabled(false);
        txtserievehi.setName("txtserievehi"); // NOI18N
        txtserievehi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtserievehiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtserievehiFocusLost(evt);
            }
        });
        txtserievehi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtserievehiKeyPressed(evt);
            }
        });

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N

        txtplaca.setForeground(resourceMap.getColor("txtplaca.foreground")); // NOI18N
        txtplaca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtplaca.setEnabled(false);
        txtplaca.setName("txtplaca"); // NOI18N
        txtplaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtplacaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtplacaFocusLost(evt);
            }
        });
        txtplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtplacaKeyPressed(evt);
            }
        });

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        txtpoliza.setForeground(resourceMap.getColor("txtpoliza.foreground")); // NOI18N
        txtpoliza.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpoliza.setEnabled(false);
        txtpoliza.setName("txtpoliza"); // NOI18N
        txtpoliza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpolizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpolizaFocusLost(evt);
            }
        });
        txtpoliza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpolizaKeyPressed(evt);
            }
        });

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        txtcertificado.setForeground(resourceMap.getColor("txtcertificado.foreground")); // NOI18N
        txtcertificado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcertificado.setEnabled(false);
        txtcertificado.setName("txtcertificado"); // NOI18N
        txtcertificado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcertificadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcertificadoFocusLost(evt);
            }
        });
        txtcertificado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcertificadoKeyPressed(evt);
            }
        });

        jPanel8.setBackground(resourceMap.getColor("jPanel8.background")); // NOI18N
        jPanel8.setFocusable(false);
        jPanel8.setName("jPanel8"); // NOI18N

        jLabel15.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel15.setForeground(resourceMap.getColor("jLabel15.foreground")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15)
        );

        jPanel9.setBackground(resourceMap.getColor("jPanel9.background")); // NOI18N
        jPanel9.setFocusable(false);
        jPanel9.setName("jPanel9"); // NOI18N

        jLabel16.setFont(resourceMap.getFont("jLabel16.font")); // NOI18N
        jLabel16.setForeground(resourceMap.getColor("jLabel16.foreground")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
        );

        jPanel10.setBackground(resourceMap.getColor("jPanel10.background")); // NOI18N
        jPanel10.setFocusable(false);
        jPanel10.setName("jPanel10"); // NOI18N

        jLabel17.setFont(resourceMap.getFont("jLabel17.font")); // NOI18N
        jLabel17.setForeground(resourceMap.getColor("jLabel17.foreground")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17)
        );

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        txtcliente.setForeground(resourceMap.getColor("txtcliente.foreground")); // NOI18N
        txtcliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcliente.setEnabled(false);
        txtcliente.setName("txtcliente"); // NOI18N
        txtcliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtclienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtclienteFocusLost(evt);
            }
        });
        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclienteKeyPressed(evt);
            }
        });

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        txtdireccion.setForeground(resourceMap.getColor("txtdireccion.foreground")); // NOI18N
        txtdireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdireccion.setEnabled(false);
        txtdireccion.setName("txtdireccion"); // NOI18N
        txtdireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdireccionFocusLost(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
        });

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        txtdni.setForeground(resourceMap.getColor("txtdni.foreground")); // NOI18N
        txtdni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdni.setEnabled(false);
        txtdni.setName("txtdni"); // NOI18N
        txtdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdniFocusLost(evt);
            }
        });
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
        });

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        txtvendedor.setEnabled(false);
        txtvendedor.setName("txtvendedor"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttipoventa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdireccion)
                            .addComponent(txtcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(42, 42, 42)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel23))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtplaca)
                            .addComponent(txtserievehi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcertificado)
                            .addComponent(txtpoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttipoventa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtpoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtserievehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setActionCommand(resourceMap.getString("jButton2.actionCommand")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        txtcajero.setEnabled(false);
        txtcajero.setName("txtcajero"); // NOI18N

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setActionCommand(resourceMap.getString("jButton5.actionCommand")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel3.AccessibleContext.accessibleName")); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        BuscaInterno();
}//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscaInterno();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        UpdateVentaSoat();
}//GEN-LAST:event_jButton3ActionPerformed

    public void UpdateVentaSoat(){
        if (txtserievehi.getText().trim().compareTo("") != 0 || txtplaca.getText().trim().compareTo("") != 0
                || txtpoliza.getText().trim().compareTo("") != 0 || txtcertificado.getText().trim().compareTo("") != 0 ) {
                              
            Confirmar pe = new Confirmar(objetoventana, "<html> SEGURO DE ACTUALIZAR LA VENTA PARA SOAT </html>");
            pe.show(true);
            if (pe.getConfirmar() == 1) {
                ActualizarVentaSOAT();
            }
        }else{
            JOptionPane.showMessageDialog(this, "POR FAVOR COMPLETE TODOS LOS DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Oculta_Botones(true);
        jButton3.setEnabled(false);
        jButton5.setEnabled(true);
    }
    public void ActualizarVentaSOAT(){
        String resultado = "";
        String interno = "";
        String serievehi = "";
        String placavehi = "";
        String polizavehi = "";
        String certificadovehi = "";
        try {
            interno = String.valueOf(jTextField1.getText().trim());
            serievehi = String.valueOf(txtserievehi.getText().trim());
            placavehi = String.valueOf(txtplaca.getText().trim());
            //polizavehi = String.valueOf(txtpoliza.getText().trim());
            certificadovehi = String.valueOf(txtcertificado.getText().trim());

            resultado = onjproforma.modificaventaSoat(interno,serievehi,placavehi,polizavehi,certificadovehi);


            //if (listdetalleProforma.size() > 0 && resultado.compareTo("") != 0) {
            if (resultado.compareTo("") != 0) {
                JOptionPane.showMessageDialog(this, " SE MODIFICO LA VENTA ", "Error", JOptionPane.INFORMATION_MESSAGE);

                LimpiatTabla();
                Limpia();
                listaInternos.removeAll(listaInternos);
                listaVenta.removeAll(listaVenta);
                interno = "";
                this.jTextField1.setEnabled(true);
                this.txtserievehi.setEnabled(false);
                this.txtplaca.setEnabled(false);
                this.txtpoliza.setEnabled(false);
                this.txtcertificado.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, " ERROR AL ACTUALIZAR LOS DATOS ", "Error", JOptionPane.ERROR_MESSAGE);
            }



        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, " ERROR AL GENERAR LA PROFORMA ", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(" ERROR AL GENERAR LA PROFORMA " + ex.getMessage());

        }

    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NuevaBusqueda();
}//GEN-LAST:event_jButton4ActionPerformed

    private void NuevaBusqueda() {
        LimpiatTabla();
        listaInternos.removeAll(listaInternos);
        listaVenta.removeAll(listaVenta);
        interno = "";
        Limpia();
        Oculta_Botones(false);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        objventas.marcacdo = false;
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void txtserievehiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtserievehiFocusGained
        // TODO add your handling code here:
        jLabel23.setForeground(new Color(98, 156, 245));
        txtserievehi.setBackground(new Color(255, 255, 102));
}//GEN-LAST:event_txtserievehiFocusGained

    private void txtserievehiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtserievehiFocusLost
        // TODO add your handling code here:
        jLabel23.setForeground(Color.black);
        txtserievehi.setBackground(new Color(255, 255, 255));
}//GEN-LAST:event_txtserievehiFocusLost

    private void txtserievehiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserievehiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if(txtserievehi.getText().equals("")){
                JOptionPane msg = new JOptionPane();
                msg.showMessageDialog(this, "POR FAVOR INGRESE EL NUMERO DE SERIE", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtserievehi.requestFocus();
            } else {
                txtplaca.requestFocus();
            }
        }
        RealizaOpciones(evt);
}//GEN-LAST:event_txtserievehiKeyPressed

    private void txtplacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtplacaFocusGained
        // TODO add your handling code here:
        jLabel33.setForeground(new Color(98, 156, 245));
        txtplaca.setBackground(new Color(255, 255, 102));
}//GEN-LAST:event_txtplacaFocusGained

    private void txtplacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtplacaFocusLost
        // TODO add your handling code here:
        jLabel33.setForeground(Color.black);
        txtplaca.setBackground(new Color(255, 255, 255));
}//GEN-LAST:event_txtplacaFocusLost

    private void txtplacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if(txtplaca.getText().equals("")){
                JOptionPane msg = new JOptionPane();
                msg.showMessageDialog(this, "POR FAVOR INGRESE LA PLACA DEL VEHICULO", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtplaca.requestFocus();
            } else {
                this.txtcertificado.requestFocus();
            }
        }
        RealizaOpciones(evt);
}//GEN-LAST:event_txtplacaKeyPressed

    private void txtpolizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpolizaFocusGained
        // TODO add your handling code here:
        jLabel27.setForeground(new Color(98, 156, 245));
        txtpoliza.setBackground(new Color(255, 255, 102));
}//GEN-LAST:event_txtpolizaFocusGained

    private void txtpolizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpolizaFocusLost
        // TODO add your handling code here:
        jLabel27.setForeground(Color.black);
        txtpoliza.setBackground(new Color(255, 255, 255));
}//GEN-LAST:event_txtpolizaFocusLost

    private void txtpolizaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpolizaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtpoliza.getText().equals("")){
                JOptionPane msg = new JOptionPane();
                msg.showMessageDialog(this, "POR FAVOR INGRESE NUMERO DE POLIZA", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtpoliza.requestFocus();
            } else {
                txtcertificado.requestFocus();
            }
        }
        RealizaOpciones(evt);
}//GEN-LAST:event_txtpolizaKeyPressed

    private void txtcertificadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcertificadoFocusGained
        // TODO add your handling code here:
        jLabel28.setForeground(new Color(98, 156, 245));
        txtcertificado.setBackground(new Color(255, 255, 102));
}//GEN-LAST:event_txtcertificadoFocusGained

    private void txtcertificadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcertificadoFocusLost
        // TODO add your handling code here:
        jLabel28.setForeground(Color.black);
        txtcertificado.setBackground(new Color(255, 255, 255));
}//GEN-LAST:event_txtcertificadoFocusLost

    private void txtcertificadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcertificadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if(txtcertificado.getText().equals("")){
                JOptionPane msg = new JOptionPane();
                msg.showMessageDialog(this, "POR FAVOR INGRESE NUMERO DE CERTIFICADO", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtcertificado.requestFocus();
            } else {
                jButton3.requestFocus();
            }
        }
        RealizaOpciones(evt);
}//GEN-LAST:event_txtcertificadoKeyPressed
private void CerrarVentana() {
        int response = JOptionPane.showConfirmDialog(null, " Desea Cerrar Esta Ventana ?", "Confirmar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            AplicacionVentas.marcacdo = false;
            objventas.Habilita(true);
            dispose();
        }

    }
    private void txtclienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtclienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienteFocusGained

    private void txtclienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtclienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienteFocusLost

    private void txtclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienteKeyPressed

    private void txtdireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionFocusGained

    private void txtdireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionFocusLost

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtdniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdniFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniFocusGained

    private void txtdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniFocusLost

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Modificar();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void Modificar(){
        Oculta_Botones(false);
        jButton3.setEnabled(true);
        jButton5.setEnabled(false);
        this.txtserievehi.setEnabled(true);
        this.txtplaca.setEnabled(true);
        this.txtpoliza.setEnabled(true);
        this.txtcertificado.setEnabled(true);
        this.txtserievehi.requestFocus();
        this.jTextField1.setEnabled(false);
    }
    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jButton4KeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_formKeyReleased

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jButton2KeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_formKeyPressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jPanel2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        RealizaOpciones(evt);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void BuscaInterno() {
        if (this.jTextField1.getText().trim().compareTo("") != 0) {
            if (this.jTextField1.getText().trim().length() == 6) {
                LimpiatTabla();
                listaInternos.removeAll(listaInternos);
                interno = jTextField1.getText().trim();
                obj = new Venta(idbotica, interno);
                listaInternos = logventa.Lista_Internos_Ventas_SOAT(obj, 0);

                if (listaInternos.size() > 0) {
                    this.txtcajero.setText(listaInternos.get(0).getCajero());
                    this.txtnumero.setText(listaInternos.get(0).getNumero());
                    this.txtserie.setText(listaInternos.get(0).getSerie());
                    this.txttipoventa.setText(listaInternos.get(0).getTipventa());
                    this.txtvendedor.setText(listaInternos.get(0).getNombre());
                    this.txttotal.setText(String.valueOf(listaInternos.get(0).getTotal()));
                    this.txtigv.setText(String.valueOf(listaInternos.get(0).getIGV()));
                    this.txtsubtotal.setText(String.valueOf(listaInternos.get(0).getSubTotal()));
                    this.txtserievehi.setText(String.valueOf(listaInternos.get(0).getNumeroserie()));
                    this.txtplaca.setText(String.valueOf(listaInternos.get(0).getPlaca()));
                    this.txtpoliza.setText(String.valueOf(listaInternos.get(0).getPoliza()));
                    this.txtcertificado.setText(String.valueOf(listaInternos.get(0).getCertificado()));
                    this.txtcliente.setText(String.valueOf(listaInternos.get(0).getNombre_RazonSocial()));
                    this.txtdireccion.setText(String.valueOf(listaInternos.get(0).getDireccion()));
                    this.txtdni.setText(String.valueOf(listaInternos.get(0).getDNI()));
                    CargarProductos();
                }else{
                    this.Limpia();
                    JOptionPane.showMessageDialog(this, " Esta no es una venta SOAT", "Error", JOptionPane.ERROR_MESSAGE);
                }
                Oculta_Botones(true);
                jButton3.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, " Interno Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, " Porfavor Ingrese su Numero de Interno ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /*public void ImprimirSOAT() {
        ResultadoVenta objresultado = null;

        interno = jTextField1.getText().trim();
        objresultado = objguardaventa.ImprimeVentaSOAT(idbotica,interno);

    }*/

    private void Limpia() {
        this.jTextField1.setText("");
        this.txtserie.setText("");
        this.txtnumero.setText("");
        this.txtcajero.setText("");
        this.txtsubtotal.setText("");
        this.txttipoventa.setText("");
        this.txttotal.setText("");
        this.txtvendedor.setText("");
        this.txtigv.setText("");
        this.txtserievehi.setText("");
        this.txtplaca.setText("");
        this.txtpoliza.setText("");
        this.txtcertificado.setText("");
        this.txtcliente.setText("");
        this.txtdireccion.setText("");
        this.txtdni.setText("");
    }

    private void CargarProductos() {
        String Interno = jTextField1.getText().trim();
        obj = new Venta(idbotica, Interno);
        listaVenta = logventa.ListaVenta_Detalle(obj);

        for (int i = 0; i < listaVenta.size(); i++) {
            datosDetalle_1[0] = i + 1;
            datosDetalle_1[1] = listaVenta.get(i).getDescr_Producto();
            datosDetalle_1[2] = listaVenta.get(i).getUnidad();
            datosDetalle_1[3] = listaVenta.get(i).getFraccion();
            datosDetalle_1[4] = listaVenta.get(i).getPrecio_Venta_Final();
            datosDetalle_1[5] = listaVenta.get(i).getTotal_producto();
            model.addRow(datosDetalle_1);
        }
    }

    private void LimpiatTabla() {
        int cant = model.getRowCount();
        if (cant >= 1) {
            for (int i = cant - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }
    }
    private class MuestraVentana extends JFrame {

        public MuestraVentana() {
        }
    }

    private void RealizaOpciones(java.awt.event.KeyEvent evt) {

        try {

            if (evt.getKeyText(evt.getKeyCode()).compareTo("F3") == 0) {
                //BusquedaProducto();
            } else {
                if (evt.getKeyText(evt.getKeyCode()).compareTo("F2") == 0) {
                    Modificar();
                } else {
                    if (evt.getKeyText(evt.getKeyCode()).compareTo("F9") == 0) {
                        if (jTextField1.getText().trim().compareTo("") != 0 || txtserievehi.isEnabled()) {
                               UpdateVentaSoat();      
                        }
                    } else {
                        
                            if (evt.getKeyText(evt.getKeyCode()).compareTo("F8") == 0) {
                                CerrarVentana();
                            } else {                                
                                
                                    if (evt.getKeyText(evt.getKeyCode()).compareTo("Escape") == 0) {
                                        NuevaBusqueda();
                                    } 
                                
                            }
                        
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println("RealizaOpciones " + ex.toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtcajero;
    private javax.swing.JTextField txtcertificado;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtpoliza;
    private javax.swing.JTextField txtserie;
    private javax.swing.JTextField txtserievehi;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttipoventa;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvendedor;
    // End of variables declaration//GEN-END:variables

}
