/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormNotaDebitos.java
 *
 * Created on 19/05/2017, 06:15:11 PM
 */

package sistemanortfarma;


import CapaLogica.LogicaFechaHora;
import CapaLogica.LogicaVenta;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import entidad.Venta;
import java.util.ArrayList;
import javax.print.DocFlavor.STRING;
import javax.swing.JOptionPane;


/**
 *
 * @author gparedes
 */
public class FormNotaDebitos extends javax.swing.JDialog {
    FormPersonal formpersonal;
    JFrame objetoventana;
    DefaultTableModel tabladiferencia;
    private DefaultTableModel model;
    LogicaFechaHora logicaGenerico = new LogicaFechaHora();
    LogicaVenta logventa = new LogicaVenta();
    String Id_Venta,fecha_venta;
    /** Creates new form FormNotaDebitos */
    public FormNotaDebitos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
      
    }
    public FormNotaDebitos(java.awt.Frame parent, boolean modal,String cruce, String CodPro,String cantidad,String importe, String Desc) {
        super(parent, modal);
        
        initComponents();
        llenarTabla(cruce,CodPro,cantidad, importe,Desc);
        this.setLocationRelativeTo(null);
        // model = (DefaultTableModel) jTable1.getModel();
        //jTable1.setModel(model);
    }
    private void llenarTabla(String cruce,String Cod,String cant, String Imp, String desc){
        //if(model==null){

        model=(DefaultTableModel) jTable1.getModel();
        Object[] fila = new Object[5];//Creamos un Objeto con tantos parámetros como datos retorne cada fila            // de la consulta
        fila[0] = cruce;
        fila[1] = Cod; //Lo que hay entre comillas son los campos de la base de datos
        fila[2] = desc;
        fila[3] = cant;
        fila[4] = Imp;
        model.addRow(fila);
        jTable1.setModel(model);
   }
        //tablaDiferencia = new DefaultTableModel() ;


        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbAsociarInterno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sistemanortfarma.SistemaNortfarmaApp.class).getContext().getResourceMap(FormNotaDebitos.class);
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setToolTipText(resourceMap.getString("jButton1.toolTipText")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel8.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setEnabled(false);
        jLabel8.setName("jLabel8"); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setText(resourceMap.getString("txtpersonal.text")); // NOI18N
        jTextField1.setName("txtpersonal"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setName("jTextField2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Cruce", "Codigo Producto", "Descripcion", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jbAsociarInterno.setText(resourceMap.getString("jbAsociarInterno.text")); // NOI18N
        jbAsociarInterno.setName("jbAsociarInterno"); // NOI18N
        jbAsociarInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsociarInternoActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro interno", "Fecha", "Serie", "Numero", "Nombre Producto", "unidad", "Fraccion", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName("jTable2"); // NOI18N
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setBackground(resourceMap.getColor("jLabel2.background")); // NOI18N
        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton3)
                        .addGap(134, 134, 134)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jbAsociarInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jbAsociarInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       muestra_Personal();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
       // this.RealizaOpciones(evt);
}//GEN-LAST:event_jButton1KeyPressed

    private void jbAsociarInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsociarInternoActionPerformed

        llenarInternos(jTable1.getValueAt(0, 1).toString());
    }//GEN-LAST:event_jbAsociarInternoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un trabajador","Error", JOptionPane.ERROR_MESSAGE);
        }
        if(jTable2.getSelectedRowCount()<=0 || Id_Venta.equals("") || fecha_venta.equals("")){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un interno de Venta \n Doble click para seleccionar","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        GuardarCruce_Trabajador();
        JOptionPane.showMessageDialog(this, "Nota de Debito generada correctamente");
        // para guardar
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if(evt.getClickCount()<=1)
            return;
        Id_Venta=jTable2.getValueAt(0, 0).toString();
        fecha_venta=jTable2.getValueAt(0, 1).toString();
        jLabel1.setText(jLabel1.getText()+ " "+Id_Venta);
        JOptionPane.showMessageDialog(this, "Interno Seleccionado");

    }//GEN-LAST:event_jTable2MouseClicked
private void muestra_Personal() {
        objetoventana=null;
        formpersonal = new FormPersonal(objetoventana);
        formpersonal.pack();
        formpersonal.setVisible(true);

        if(this.jTextField1.getText()!=null){
            this.jTextField1.setText(FormPersonal.getNombre_Personal());
            this.jTextField2.setText(FormPersonal.getIdpersonal());

        }
}
private void llenarInternos(String IdProducto){
    DefaultTableModel model2=(DefaultTableModel) jTable2.getModel();
        jTable2.setModel(model2);
        ArrayList<Venta> ventas= new ArrayList<Venta>();
        ventas=logventa.Lista_Internos_Para_Ndebito(IdProducto);

        for (int i = 0; i < ventas.size(); i++) {
            Venta temp=ventas.get(i);
            Object[] fila=new Object[8];
            fila[0]=temp.getId_Venta();
            fila[1]=temp.getFechaVta();
            fila[2]=temp.getSerie();
            fila[3]=temp.getNumero();
            fila[4]=temp.getDescr_Producto();
            fila[5]=String.valueOf(temp.getUnidad());
            fila[6]=String.valueOf(temp.getFraccion());
            fila[7]=String.valueOf(temp.getTotal_producto());
            model2.addRow(fila);
            }
        jTable2.setModel(model2);
}
private void GuardarCruce_Trabajador(){
       String Id_cruce,Id_Producto,Id_trabajador,id_venta,fecha_venta;
       Id_cruce=jTable1.getValueAt(0, 0).toString();
       Id_Producto=jTable1.getValueAt(0, 1).toString();
       double precio=Double.parseDouble(jTable1.getValueAt(0, 4).toString());
       int uniCar = logicaGenerico.RecuperaEntero(jTable1.getValueAt(0, 3).toString());
       int fraCar = logicaGenerico.RecuperaFraccion(jTable1.getValueAt(0, 3).toString());

       Id_trabajador=jTextField2.getText();
 //Se quedo alli porque se cambia formato de nota debito xD

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormNotaDebitos dialog = new FormNotaDebitos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbAsociarInterno;
    // End of variables declaration//GEN-END:variables

}
