/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IngreseCajeroPago.java
 *
 * Created on 13/01/2012, 10:32:55 AM
 */
package sistemanortfarma;

import CapaLogica.LogicaPersonal;
import entidad.Cajas;
import entidad.Personal;
import entidad.ProductosPrecios;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gino Paredes Zurita.
 */
public class IngreseOperadorRecarga extends javax.swing.JDialog {
    
    //List<Cajas> listacajas = new ArrayList<Cajas>();
    LogicaPersonal logperso = new LogicaPersonal();
    List<Personal> Lista_Operador = new ArrayList<Personal>();
    String idbotica;
    Cotizacion obj;
    RealizaVenta obj1;
    public static int IdOperadorRecarga;
    public static String DescOperadorRecarga;    

    /** Creates new form IngreseCajeroPago */    
    public IngreseOperadorRecarga(Cotizacion miobjeto, String idbtoti,String idProducto) {
        super();
        initComponents();      
        obj = miobjeto;
        idbotica = idbtoti;
        this.setLocationRelativeTo(null);
        CargarOperadorRecarga();     
    }

    public IngreseOperadorRecarga(RealizaVenta miobjeto, String idbtoti,String idProducto) {
        super();
        initComponents();
        obj1 = miobjeto;
        idbotica = idbtoti;
        this.setLocationRelativeTo(null);
        CargarOperadorRecarga();
    }
       
    public static int getIdOperadorRecarga() {
        return IdOperadorRecarga;
    }

    public static void setIdOperadorRecarga(int IdOperadorRecarga) {
        IngreseOperadorRecarga.IdOperadorRecarga = IdOperadorRecarga;
    }

    public static String getDescOperadorRecarga() {
        return DescOperadorRecarga;
    }

    public static void setDescOperadorRecarga(String DescOperadorRecarga) {
        IngreseOperadorRecarga.DescOperadorRecarga = DescOperadorRecarga;
    }




    private void CargarOperadorRecarga() {
        
        try {
        Lista_Operador = logperso.Lista_Operador();

            jComboBox2.addItem("-- Seleccionar Operador --");
        for (int i = 0; i < Lista_Operador.size(); i++) {
            jComboBox2.addItem(Lista_Operador.get(i).getDescpoperadorrec());

        }
        } catch (Exception ex) {
        }
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sistemanortfarma.SistemaNortfarmaApp.class).getContext().getResourceMap(IngreseOperadorRecarga.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel3.setFont(resourceMap.getFont("jComboBox2.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox2.setFont(resourceMap.getFont("jComboBox2.font")); // NOI18N
        jComboBox2.setForeground(resourceMap.getColor("jComboBox2.foreground")); // NOI18N
        jComboBox2.setName("jComboBox2"); // NOI18N
        jComboBox2.setPreferredSize(new java.awt.Dimension(25, 25));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox2MouseEntered(evt);
            }
        });
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox2KeyReleased(evt);
            }
        });

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x = jComboBox2.getSelectedIndex();

       if (x == 0) {
            JOptionPane.showMessageDialog(this, "PORFAVOR SELECCIONE UN OPERADOR DE TELEFONO", "Error", JOptionPane.ERROR_MESSAGE);
       }else{
           setIdOperadorRecarga(Integer.valueOf(Lista_Operador.get(jComboBox2.getSelectedIndex() -1).getid_productorecarga()));
           setDescOperadorRecarga(Lista_Operador.get(jComboBox2.getSelectedIndex() -1).getDescpoperadorrec());
           this.dispose();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Guarda_Pagos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseEntered

}//GEN-LAST:event_jComboBox2MouseEntered

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
    if (evt.getStateChange() == 2) {
    //        jComboBox1.removeAllItems();
    //        CargarCajeros();
        }
}//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        /*
        if (jComboBox2.getSelectedIndex() > 0) {
            Nomcaja = jComboBox2.getSelectedItem();
            idcaja = listacajas.get(jComboBox2.getSelectedIndex() -1).getIdcaja();
            Delivery = listacajas.get(jComboBox2.getSelectedIndex() - 1).getEsDelivery();
            MarcaDelivery= listacajas.get(jComboBox2.getSelectedIndex() - 1).getMarcadoDelivery();
            setNomcaja(Nomcaja);
            setIdcaja(idcaja);
            setDelivery(Delivery);
            setMarcaDelivery(MarcaDelivery);
            eligio = true;
        }else{
            Nomcaja ="";
            idcaja = -1;
            eligio = false;
        }*/

        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (eligio) {
                this.hide();
            }
        }
        if (evt.getKeyCode() == 27) {
            this.hide();
        }*/
        
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyReleased

}//GEN-LAST:event_jComboBox2KeyReleased

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        Guarda_Pagos();
    }//GEN-LAST:event_jButton2KeyPressed

    private void Guarda_Pagos() {
       int x = jComboBox2.getSelectedIndex();
       if (x == 0) {
            JOptionPane.showMessageDialog(this, "PORFAVOR SELECCIONE UN OPERADOR DE TELEFONO", "Error", JOptionPane.ERROR_MESSAGE);
       }else{
            setIdOperadorRecarga(Integer.valueOf(Lista_Operador.get(jComboBox2.getSelectedIndex() -1).getid_productorecarga()));
            setDescOperadorRecarga(Lista_Operador.get(jComboBox2.getSelectedIndex() -1).getDescpoperadorrec());
       this.hide();
       }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables


}
